export const ADD_PROD = 'ADD_PROD';
export const CHANGE_PROD = 'CHANGE_PROD';
export const REMOVE_PROD = 'REMOVE_PROD';

export const ADD_WAREHOUSE = 'ADD_WAREHOUSE';
export const CHANGE_WAREHOUSE = 'CHANGE_WAREHOUSE';
export const REMOVE_WAREHOUSE = 'REMOVE_WAREHOUSE';
