export const ADD_PROD = 'ADD_PROD';
export const CHANGE_PROD = 'CHANGE_PROD';
export const REMOVE_PROD = 'REMOVE_PROD';

export const ADD_WAREHOUSES = 'ADD_WAREHOUSES';
export const CHANGE_WAREHOUSES = 'CHANGE_WAREHOUSES';
export const REMOVE_WAREHOUSES = 'REMOVE_WAREHOUSES';
export const WAREHOUSES_FROM_GENERAL = 'WAREHOUSES_FROM_GENERAL';

export const REMOVE_PROD_FROM_WARE = 'REMOVE_PROD_FROM_WARE';
export const REMOVE_ALL_PROD_FROM_WARE = 'REMOVE_ALL_PROD_FROM_WARE';
export const WAREHOUSE_FROM_GENERAL = 'WAREHOUSE_FROM_GENERAL';
export const ADD_PROD_IN_WAREHOUSE = 'ADD_PROD_IN_WAREHOUSE';

export const MOVE_PROD_IN_WARE = 'MOVE_PROD_IN_WARE';
export const MOVE_PROD_FROM_WARE = 'MOVE_PROD_FROM_WARE';

